A start towards making the install script work on Manjaro
Currently the script assumes you are using a distro with apt-get. I
recently started looking at Manjaro which is based off of Arch, which
means that the package manager now is pacman, not apt-get.

This change does not fix all the problems, but it at least allows some
programs to be installed now. There is no support currently for
updating, or for adding new repos, and some programs still fail to
install because the package names appear to be different.

diff --git a/.auto-install-programs/install-programs-helper b/.auto-install-programs/install-programs-helper
--- a/.auto-install-programs/install-programs-helper
+++ b/.auto-install-programs/install-programs-helper
@@ -6,6 +6,16 @@ readarray PROGRAMS_USER_INTERACT < ~/.auto-install-programs/programs-to-install-
 readarray PROGRAMS_LONG < ~/.auto-install-programs/programs-to-install-long.cfg
 readarray REPOS < ~/.auto-install-programs/repos-to-add.cfg
 
+echo "OS is $OS"
+if [[ $OS  == "Debian" ]]; then
+  install_cmd="sudo apt-get -y install"
+elif [[ $OS  == "Manjaro" ]]; then
+  install_cmd="sudo pacman -S --noconfirm"
+else
+  echo "Could not determine what package manager to use."
+  exit 1
+fi
+
 COMPLETED=()
 FAILED=()
 
@@ -61,7 +71,7 @@ then
 
     echo "------------------------------------------------------------"
     echo "Start Installation - $PROGRAM"
-    sudo apt-get -y install $PROGRAM
+    $install_cmd $PROGRAM
     if [ $? -eq 0 ]
     then
       echo " "
@@ -98,7 +108,7 @@ then
 
     echo "------------------------------------------------------------"
     echo "Start Installation - $PROGRAM"
-    sudo apt-get -y install $PROGRAM
+    $install_cmd $PROGRAM
     if [ $? -eq 0 ]
     then
       echo " "
@@ -132,7 +142,7 @@ do
 
   echo "------------------------------------------------------------"
   echo "Start Installation - $PROGRAM"
-  sudo apt-get -y install $PROGRAM
+  $install_cmd $PROGRAM
   if [ $? -eq 0 ]
   then
     echo " "
