Updated install script.
now I have separated programs that take a long time to install.

There is also now a prompt for the user to install the long programs, and the
programs that require user interaction.

diff --git a/.auto-install-programs/install-programs-helper b/.auto-install-programs/install-programs-helper
--- a/.auto-install-programs/install-programs-helper
+++ b/.auto-install-programs/install-programs-helper
@@ -2,6 +2,7 @@
 
 readarray PROGRAMS < ~/.auto-install-programs/programs-to-install
 readarray PROGRAMS_USER_INTERACT < ~/.auto-install-programs/programs-to-install-require-user-interaction
+readarray PROGRAMS_LONG < ~/.auto-install-programs/programs-to-install-long
 readarray REPOS < ~/.auto-install-programs/repos-to-add
 
 COMPLETED=()
@@ -11,11 +12,20 @@ if [[ ${PROGRAMS_USER_INTERACT[@]} > 0 ]]
 then
   echo "There are programs that are set to be installed that may require user interaction."
   echo "These programs will be installed first, so that this script can be left alone as soon as possible."
-  echo "Please stay at the computer until a Message displays that says you can. The script will pause for this..."
-  read -p "Press [enter] to continue..."
+  echo " "
+  echo "Install these programs [yN]? "
+  read do_user_interaction
 fi
 
-## add repositories
+if [[ ${PROGRAMS_LONG[@]} > 0 ]]
+then
+  echo "There are programs that are set to be installed that may take a significant amount of time to install"
+  echo " "
+  echo "Install these programs [yN]? "
+  read do_long
+fi
+
+# add repositories
 for REPO in ${REPOS[@]}
 do
   echo "------------------------------------------------------------"
@@ -33,33 +43,68 @@ echo " "
 echo " "
 
 
-# This is for programs that may require user interaction
-for PROGRAM in ${PROGRAMS_USER_INTERACT[@]}
-do
-  echo "------------------------------------------------------------"
-  echo "Start Installation - $PROGRAM"
-  sudo apt-get -y install $PROGRAM
-  if [ $? -eq 0 ]
-  then
-    echo " "
-    echo " "
-    echo "Install COMPLETED Successfully - $PROGRAM"
+if [[ $do_user_interaction = "y" ||$do_user_interaction = "Y" ]]
+then
+  # This is for programs that may require user interaction
+  for PROGRAM in ${PROGRAMS_USER_INTERACT[@]}
+  do
     echo "------------------------------------------------------------"
-    echo " "
-    echo " "
-    COMPLETED+=($PROGRAM)
-  else
-    echo " "
-    echo " "
-    echo "Install FAILED - $PROGRAM"
+    echo "Start Installation - $PROGRAM"
+    sudo apt-get -y install $PROGRAM
+    if [ $? -eq 0 ]
+    then
+      echo " "
+      echo " "
+      echo "Install COMPLETED Successfully - $PROGRAM"
+      echo "------------------------------------------------------------"
+      echo " "
+      echo " "
+      COMPLETED+=($PROGRAM)
+    else
+      echo " "
+      echo " "
+      echo "Install FAILED - $PROGRAM"
+      echo "------------------------------------------------------------"
+      echo " "
+      echo " "
+      FAILED+=($PROGRAM)
+    fi
+    echo "The programs that may have required user interaction are now installed!"
+    read -p "Press [enter] to continue..."
+  done
+fi
+
+
+if [[ $do_long = "y" ||$do_long = "Y" ]]
+then
+  # This is for programs that may require user interaction
+  for PROGRAM in ${PROGRAMS_USER_INTERACT[@]}
+  do
     echo "------------------------------------------------------------"
-    echo " "
-    echo " "
-    FAILED+=($PROGRAM)
-  fi
-  echo "The programs that may have required user interaction are now installed!"
-  read -p "Press [enter] to continue..."
-done
+    echo "Start Installation - $PROGRAM"
+    sudo apt-get -y install $PROGRAM
+    if [ $? -eq 0 ]
+    then
+      echo " "
+      echo " "
+      echo "Install COMPLETED Successfully - $PROGRAM"
+      echo "------------------------------------------------------------"
+      echo " "
+      echo " "
+      COMPLETED+=($PROGRAM)
+    else
+      echo " "
+      echo " "
+      echo "Install FAILED - $PROGRAM"
+      echo "------------------------------------------------------------"
+      echo " "
+      echo " "
+      FAILED+=($PROGRAM)
+    fi
+    echo "The programs that may have required user interaction are now installed!"
+    read -p "Press [enter] to continue..."
+  done
+fi
 
 
 for PROGRAM in ${PROGRAMS[@]}
