Changed the install instructions for youtube-dl
Apt-get has an old version of youtube-dl. Now the program is installed
as recommended by the dev.

diff --git a/.auto-install-programs/install-programs-helper b/.auto-install-programs/install-programs-helper
--- a/.auto-install-programs/install-programs-helper
+++ b/.auto-install-programs/install-programs-helper
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 readarray PROGRAMS < ~/.auto-install-programs/programs-to-install.cfg
+readarray PROGRAMS_CMD < ~/.auto-install-programs/programs-to-install-command.cfg
 readarray PROGRAMS_USER_INTERACT < ~/.auto-install-programs/programs-to-install-require-user-interaction.cfg
 readarray PROGRAMS_LONG < ~/.auto-install-programs/programs-to-install-long.cfg
 readarray REPOS < ~/.auto-install-programs/repos-to-add.cfg
@@ -132,6 +133,36 @@ do
   echo "------------------------------------------------------------"
   echo "Start Installation - $PROGRAM"
   sudo apt-get -y install $PROGRAM
+  if [ $? -eq 0 ]
+  then
+    echo " "
+    echo " "
+    echo "Install COMPLETED Successfully - $PROGRAM"
+    echo "------------------------------------------------------------"
+    echo " "
+    echo " "
+    COMPLETED+=($PROGRAM)
+  else
+    echo " "
+    echo " "
+    echo "Install FAILED - $PROGRAM"
+    echo "------------------------------------------------------------"
+    echo " "
+    echo " "
+    FAILED+=($PROGRAM)
+  fi
+done
+
+for PROGRAM in "${PROGRAMS_CMD[@]}"
+do
+  # Skip comments when parsing
+  [[ ${PROGRAM:0:1} == "#" ]] && continue
+  # Skip empty lines when parsing
+  [[ ${PROGRAM:1:1} == "" ]] && continue
+
+  echo "------------------------------------------------------------"
+  echo "Start Installation - $PROGRAM"
+  $PROGRAM
   if [ $? -eq 0 ]
   then
     echo " "
