Ran shellcheck on script, and added a function

diff --git a/update-all-repos b/update-all-repos
--- a/update-all-repos
+++ b/update-all-repos
@@ -2,45 +2,32 @@
 
 # Update ~/ with new pulled dotfiles
 echo "Updating remote-github/dotfiles"
-cd ~/Documents/git-repos/remote-github/dotfiles
+# Try to go to this directory... If it fails, exit the script
+cd ~/Documents/git-repos/remote-github/dotfiles || exit
 git pull
 ./sym-link-files-to-home
 
+function updateRepo {
+  # if $1 is empty, exit
+  if [ -z "$1" ]; then
+    echo "Function updateRepo() expects 1 argument"
+    exit
+  fi
 
-cd ~/Documents/git-repos/remote-github
+  cd ~/Documents/git-repos/"$1" || exit
 
-REPO_NAMES=(*)
+  REPO_NAMES=(*)
 
-for REPO in ${REPO_NAMES[@]}
-do
-  cd $REPO
-  echo "Updating remote-github/${REPO}..."
-  git pull
-  cd ..
-done
+  for REPO in "${REPO_NAMES[@]}"
+  do
+    cd $REPO || exit
+    echo "Updating $1/${REPO}..."
+    git pull
+    cd ..
+  done
+}
 
-
-cd ~/Documents/git-repos/repos-i-contribute-to
-
-REPO_NAMES=(*)
-
-for REPO in ${REPO_NAMES[@]}
-do
-  cd $REPO
-  echo "Updating repos-i-contribute-to/${REPO}..."
-  git pull
-  cd ..
-done
-
-cd ~/Documents/git-repos/useful-repos
-
-REPO_NAMES=(*)
-
-for REPO in ${REPO_NAMES[@]}
-do
-  cd $REPO
-  echo "Updating useful-repos/${REPO}..."
-  git pull
-  cd ..
-done
+updateRepo "remote-github"
+updateRepo "repos-i-contribute-to"
+updateRepo "useful-repos"
 
