Updated my update script to work with manjaro

diff --git a/.my-scripts/update b/.my-scripts/update
--- a/.my-scripts/update
+++ b/.my-scripts/update
@@ -1,10 +1,19 @@
 #!/bin/bash
 
+echo "OS is $OS"
+if [[ $OS  == "Debian" ]]; then
+  update_cmd="sudo apt-get update && sudo apt-get -y dist-upgrade"
+elif [[ $OS  == "Manjaro" ]]; then
+  update_cmd="sudo pacman -Syyu --noconfirm"
+else
+  echo "Could not determine what package manager to use."
+  exit 1
+fi
+
 echo " " ;
 echo "==========================================="
 echo "Ready to Update..."
-sudo apt-get update
-sudo apt-get -y dist-upgrade
+$update_cmd
 echo " "
 echo "Update Complete!"
 echo "==========================================="
